from finta import TA

indicator_map = {
    "ta.sma": TA.SMA,
    "ta.smm": TA.SMM,
    "ta.ssma": TA.SSMA,
    "ta.ema": TA.EMA,
    "ta.dema": TA.DEMA,
    "ta.tema": TA.TEMA,
    "ta.trima": TA.TRIMA,
    "ta.vama": TA.VAMA,
    "ta.er": TA.ER,
    "ta.kama": TA.KAMA,
    "ta.zelma": TA.ZLEMA,
    "ta.wma": TA.WMA,
    "ta.hma": TA.HMA,
    "ta.evwma":TA.EVWMA,
    "ta.vwap":TA.VWAP,
    "ta.smma":TA.SMMA,
    "ta.macd":TA.MACD,
    "ta.ppo":TA.PPO,
    "ta.vw_macd":TA.VW_MACD,
    "ta.ev_macd":TA.EV_MACD,
    "ta.mom":TA.MOM,
    "ta.roc":TA.ROC,
    "ta.rsi":TA.RSI,
    "ta.ift_rsi":TA.IFT_RSI,
    "ta.tr":TA.TR,
    "ta.atr":TA.ATR,
    "ta.sar":TA.SAR,
    "ta.bbands":TA.BBANDS,
    "ta.bbwidth":TA.BBWIDTH,
    "ta.percent_b":TA.PERCENT_B,
    "ta.kc":TA.KC,
    "ta.do":TA.DO,
    "ta.dmi":TA.DMI,
    "ta.adx":TA.ADX,
    "ta.pivot":TA.PIVOT,
    "ta.pivot_fib":TA.PIVOT_FIB,
    "ta.stoch":TA.STOCH,
    "ta.stochd":TA.STOCHD,
    "ta.stochrsi":TA.STOCHRSI,
    "ta.williams":TA.WILLIAMS,
    "ta.uo":TA.UO,
    "ta.ao":TA.AO,
    "ta.mi":TA.MI,
    "ta.vortex":TA.VORTEX,
    "ta.kst":TA.KST,
    "ta.tsi":TA.TSI,
    "ta.tp":TA.TP,
    "ta.adl":TA.ADL,
    "ta.chaikin":TA.CHAIKIN,
    "ta.mfi":TA.MFI,
    "ta.obv":TA.OBV,
    "ta.wobv":TA.WOBV,
    "ta.vzo":TA.VZO,
    "ta.pzo":TA.PZO,
    "ta.efi":TA.EFI,
    "ta.cfi":TA.CFI,
    "ta.ebbp":TA.EBBP,
    "ta.emv":TA.EMV,
    "ta.cci":TA.CCI,
    "ta.copp":TA.COPP,
    "ta.basp":TA.BASP,
    "ta.baspn":TA.BASPN,
    "ta.cmo":TA.CMO,
    "ta.chandelier":TA.CHANDELIER,
    "ta.qstick":TA.QSTICK,
    "ta.tmf":TA.TMF,
    "ta.wto":TA.WTO,
    "ta.fish":TA.FISH,
    "ta.ichimoku":TA.ICHIMOKU,
    "ta.apz":TA.APZ,
    "ta.vr":TA.VR,
    "ta.sqzmi":TA.SQZMI,
    "ta.vpt":TA.VPT,
    "ta.fve":TA.FVE,
    "ta.vfi":TA.VFI,
    "ta.msd":TA.MSD,
}
